version: "3"
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: diploma-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diploma
    ports:
      - "35432:5432"
  localstack:
    container_name: localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    volumes:
      - ./storage:/docker-entrypoint-initaws.d
