server:
  port: 8080

feign:
  client:
    config:
      user:
        connect-timeout: 50000
        read-timeout: 30000

services:
  user:
    url: 'http://localhost:9090'
spring:
  .security:
    secret: "SECRET"
    refresh-secret: "REFRESH-SECRET"
    session-duration-minutes: 86400
    allowed-origin: "http://localhost:3000"
    csrf:
      xsrf_cookie_name: 'MH-XSRF'
      xsrf_header_name: "MH-X-XSRF"
      cookie_domain: "localhost"
    success-redirect-url: "/my-profile"

