server:
  port: 8080

feign:
  client:
    config:
      user:
        connect-timeout: 50000
        read-timeout: 30000

services:
  user:
    url: 'http://localhost:7090'
  file:
    url: 'http://localhost:7091'
  conversation:
    url: 'http://localhost:7093'
  maps:
    url: 'https://maps.googleapis.com/maps'
security:
  secret: "SECRET"
  refresh-secret: "REFRESH-SECRET"
  allowed-origin: "http://localhost:3000"
csrf:
  xsrf_cookie_name: 'XSRF'
  xsrf_header_name: "X-XSRF"
  cookie_domain: "localhost"
jwt:
  access_token_name: "JWT"
  refresh_token_name: "JWT_REFRESH"
spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
avatar:
  user_postfix: '_avatar.png'
  default: 'default_avatar.png'
video_presentation:
  tutor_postfix: '_tutor_video-presentations.mp4'
  student_postfix: '_student_video-presentations.mp4'
geocoding:
  key: 'AIzaSyAJ7QA6FkbHEVQXQlUH0rq2nuS0Khv1HUc'
aws:
  avatar_storage_name: avatars
  tutors_video_presentation_storage_name: video-presentations-tutors
  students_video_presentation_storage_name: video-presentations-students
