server:
  port: 8080

feign:
  client:
    config:
      user:
        connect-timeout: 50000
        read-timeout: 30000

services:
  user:
    url: 'http://localhost:9090'
  file:
    url: 'http://localhost:9091'
security:
  secret: "SECRET"
  refresh-secret: "REFRESH-SECRET"
  allowed-origin: "http://localhost:3000"
csrf:
  xsrf_cookie_name: 'XSRF'
  xsrf_header_name: "X-XSRF"
  cookie_domain: "localhost"
jwt:
  access_token_name: "JWT"
  refresh_token_name: "JWT_REFRESH"
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
avatar:
  user_postfix: '_avatar.png'
  default: 'default_avatar.png'
