server:
  port: 9091
aws:
  region: us-east-1
  s3_endpoint: http://localhost:4566/
  access_key: foo
  secret_key: bar
  avatar_storage_name: avatars-test
  tutors_video_presentation_storage_name: video-presentations-tutors-test
  students_video_presentation_storage_name: video-presentations-students-test
avatar:
  user_postfix: '_avatar.png'
  default: 'default_avatar.png'
video_presentation:
  tutor_postfix: '_tutor_video-presentations.mp4'
  student_postfix: '_student_video-presentations.mp4'
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/diploma
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB