server:
  port: 9093
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/diploma
services:
  user:
    url: 'http://localhost:9090'
  file:
    url: 'http://localhost:9091'
  places:
    url: 'https://maps.googleapis.com/maps/api/place/textsearch/json'
conversations:
  initStatus: 1
places-key: 'AIzaSyAJ7QA6FkbHEVQXQlUH0rq2nuS0Khv1HUc'
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
